//! MCP tool surface — minimal core primitives per SPEC: tab management,
//! navigate, evaluate (arbitrary in-page JS — the interaction primitive),
//! screenshot, cookies.read (credential vault), download.

// `tool_box!` below expands to one enum variant per tool struct, so every
// variant inherits the `<Command>Tool` naming this crate uses for the structs.
// The variant names are generated by the macro, not chosen here, and renaming
// the structs to satisfy the lint would break that convention. An attribute on
// the invocation itself is ignored (`unused_attributes`), so the allow is
// module-scoped.
#![allow(clippy::enum_variant_names)]

use rust_mcp_sdk::macros::{mcp_tool, JsonSchema};
use rust_mcp_sdk::schema::schema_utils::CallToolError;
use rust_mcp_sdk::schema::{CallToolResult, TextContent};
use rust_mcp_sdk::tool_box;
use serde_json::json;
use talaria_protocol::{Command, Outcome, ResultPayload};

use crate::socket::ShellConnection;

#[mcp_tool(
    name = "tabs_list",
    description = "List all open browser tabs (both the user's and agent-owned), with tab_id, url, title, and owner."
)]
#[derive(Debug, ::serde::Deserialize, ::serde::Serialize, JsonSchema)]
pub struct TabsListTool {}

#[mcp_tool(
    name = "tabs_open",
    description = "Open a new browser tab owned by this agent session at the given URL. Waits for the page to finish loading (up to ~20s) and returns the tab (tab_id, final url, title, loading flag) — if `loading` is still true the page was slow; poll tabs_list before acting."
)]
#[derive(Debug, ::serde::Deserialize, ::serde::Serialize, JsonSchema)]
pub struct TabsOpenTool {
    /// Absolute URL to open (e.g. "https://example.com").
    pub url: String,
}

#[mcp_tool(name = "tabs_close", description = "Close a browser tab by tab_id.")]
#[derive(Debug, ::serde::Deserialize, ::serde::Serialize, JsonSchema)]
pub struct TabsCloseTool {
    pub tab_id: u64,
}

#[mcp_tool(
    name = "tabs_focus",
    description = "Make a tab the active one in its view (Me or Agents) so it is rendered and receives input."
)]
#[derive(Debug, ::serde::Deserialize, ::serde::Serialize, JsonSchema)]
pub struct TabsFocusTool {
    pub tab_id: u64,
}

#[mcp_tool(
    name = "navigate",
    description = "Navigate an existing tab to a URL. Waits for the new page to finish loading (up to ~20s) and returns the tab (final url, title, loading flag), so a following evaluate runs in the new page."
)]
#[derive(Debug, ::serde::Deserialize, ::serde::Serialize, JsonSchema)]
pub struct NavigateTool {
    pub tab_id: u64,
    pub url: String,
}

#[mcp_tool(
    name = "evaluate",
    description = "Run arbitrary JavaScript in a tab's page and return the result as JSON. This is the primary interaction primitive: query the DOM, click elements, fill and submit forms, extract data — write the whole interaction as one script instead of many small tool calls. The value of the last expression is returned. Promises are awaited until they settle (up to the command timeout), and top-level `await` works: a single expression is returned as-is; a multi-statement script runs inside an async function, so end it with `return <value>`. Return plain data (strings, numbers, arrays, objects); DOM nodes come back as opaque handles. Keep cross-call state on `window`. (On pages whose CSP forbids eval, scripts still run but promises are not awaited — store results on `window` and poll.)"
)]
#[derive(Debug, ::serde::Deserialize, ::serde::Serialize, JsonSchema)]
pub struct EvaluateTool {
    pub tab_id: u64,
    /// JavaScript source. The value of the final expression is returned.
    pub script: String,
}

#[mcp_tool(
    name = "screenshot",
    description = "Capture a PNG screenshot of a tab's viewport. Returns an image."
)]
#[derive(Debug, ::serde::Deserialize, ::serde::Serialize, JsonSchema)]
pub struct ScreenshotTool {
    pub tab_id: u64,
}

#[mcp_tool(
    name = "cookies_read",
    description = "Read stored credential-vault entries (username/password/cookies) matching a domain, for reusing the user's existing sessions. Not for performing fresh logins — ask the user to take over in the browser for those."
)]
#[derive(Debug, ::serde::Deserialize, ::serde::Serialize, JsonSchema)]
pub struct CookiesReadTool {
    /// Domain to match, e.g. "github.com" (subdomains match too).
    pub domain: String,
}

#[mcp_tool(
    name = "download",
    description = "Download a URL to the user's downloads directory under the given filename. (This fetch uses a plain HTTP client rather than the browser's own network stack, so it carries none of the page's session cookies — a URL behind a login will silently return the login page instead of the file. For those, ask the user to take over and download it, or extract the resource with `evaluate` from inside the logged-in page. A size cap applies, 2 GiB by default and tunable through TALARIA_MAX_DOWNLOAD_BYTES; exceeding it aborts the download and removes the partial file. An existing file of the same name is never overwritten — the download is saved under a uniquified name like `report (1).pdf`, and the returned path is the one actually written.)"
)]
#[derive(Debug, ::serde::Deserialize, ::serde::Serialize, JsonSchema)]
pub struct DownloadTool {
    pub url: String,
    /// Plain filename, no directory components.
    pub filename: String,
}

tool_box!(
    TalariaTools,
    [
        TabsListTool,
        TabsOpenTool,
        TabsCloseTool,
        TabsFocusTool,
        NavigateTool,
        EvaluateTool,
        ScreenshotTool,
        CookiesReadTool,
        DownloadTool
    ]
);

pub async fn dispatch(
    connection: &ShellConnection,
    client: &str,
    tool: TalariaTools,
) -> Result<CallToolResult, CallToolError> {
    let command = match &tool {
        TalariaTools::TabsListTool(_) => Command::TabsList,
        TalariaTools::TabsOpenTool(t) => Command::TabsOpen { url: t.url.clone() },
        TalariaTools::TabsCloseTool(t) => Command::TabsClose { tab_id: t.tab_id },
        TalariaTools::TabsFocusTool(t) => Command::TabsFocus { tab_id: t.tab_id },
        TalariaTools::NavigateTool(t) => Command::Navigate { tab_id: t.tab_id, url: t.url.clone() },
        TalariaTools::EvaluateTool(t) => Command::Evaluate { tab_id: t.tab_id, script: t.script.clone() },
        TalariaTools::ScreenshotTool(t) => Command::Screenshot { tab_id: t.tab_id },
        TalariaTools::CookiesReadTool(t) => Command::CookiesRead { domain: t.domain.clone() },
        TalariaTools::DownloadTool(t) => Command::Download { url: t.url.clone(), filename: t.filename.clone() },
    };

    let outcome = connection
        .request(client, command)
        .await
        .map_err(CallToolError::from_message)?;

    let result = match outcome {
        Outcome::Error { message } => return Err(CallToolError::from_message(message)),
        Outcome::Ok { result } => result,
    };

    Ok(match result {
        ResultPayload::Screenshot { png_base64, width, height } => {
            let mut meta = serde_json::Map::new();
            meta.insert("width".into(), json!(width));
            meta.insert("height".into(), json!(height));
            CallToolResult::image_content(vec![rust_mcp_sdk::schema::ImageContent::new(
                png_base64,
                "image/png".into(),
                None,
                Some(meta),
            )])
        },
        ResultPayload::Tabs { tabs } => text_result(&json!({ "tabs": tabs })),
        ResultPayload::Tab { tab } => text_result(&json!({ "tab": tab })),
        ResultPayload::Value { value } => text_result(&json!({ "value": value })),
        ResultPayload::Credentials { entries } => text_result(&json!({ "entries": entries })),
        ResultPayload::Download { path, bytes } => {
            text_result(&json!({ "path": path, "bytes": bytes }))
        },
        ResultPayload::Empty {} => text_result(&json!({ "ok": true })),
    })
}

fn text_result(value: &serde_json::Value) -> CallToolResult {
    CallToolResult::text_content(vec![TextContent::from(value.to_string())])
}
